cc_test(
    name = "test_cpp",
    srcs = ["test_cpp.cc"],
    linkopts = ["-nostartfiles"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "test_c",
    srcs = ["test_c.c"],
    linkopts = ["-nostartfiles"],
    visibility = ["//visibility:public"],
)
